baseURL = "/"
title = "Tony Klausing"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

[pagination]
  pagerSize = 10000

preserveTaxonomyNames = true

[markup.goldmark.renderer] 
  unsafe= true

[params]
  description = "I'm a US-based software engineer interested in economic history, art, travel, freedom of expression, and bitcoin."
  dateFormat = "Jan 2, 2006"
  copyrightOwner = "TK"
  copyrightStartYear = "2026"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  hideSocialMenu = false
  showReadTime = true

[params.widgets]
  homepage = ["recent_posts"]

[params.assets]
  customCSS = ["css/custom.css","css/prism.css"]
  customJS = ["js/custom.js,js/prism.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"
[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Tony"

[author.social]
  codepen = ""
  email = ""
  facebook = ""
  github = "toneloc"
  instagram = ""
  twitter = "tonklaus"
  linkedin = "tonyklausing"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "About"
  weight = -70
  url = "/"

[[menu.main]]
  name = "Blog"
  url = "/posts"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
[languages.en]
  lang = "en"
  languageName = "English"
  weight = 1

[params.opengraph.facebook]
  admins = [] # array of Facebook IDs
  appID = ""
  pageID = ""